name: Compile LaTeX document and upload the project's website

on:
  workflow_call:
    inputs:
      retention_days:
        required: true
        type: string


jobs:
  build-website:
    name: Compile LaTeX document and upload the project's website
    runs-on: ubuntu-latest
    steps:
      - name: Update apt-get
        run: sudo apt-get update

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Prepare directory for downloading
        run: mkdir -p build/release

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-release
          path: build/release

      - name: Download already bundled TeX Live distribution
        run: |
          TEXLIVE_ASSET="https://github.com/kipiberbatov/texlive-packages/releases/download/v2025.0/texlive-2025.tar.gz"
          curl --silent --location $TEXLIVE_ASSET -o texlive.tar.gz

      - name: Setup TeX Live
        run: |
          mkdir -p $HOME/texlive
          echo "Unpacking TeX Live..."
          tar -xzf texlive.tar.gz -C $HOME/texlive
          TEXLIVE_BIN_DIR=$(find $HOME/texlive -type d -name "x86_64-linux")
          echo "Adding $TEXLIVE_BIN_DIR to PATH"
          echo "$TEXLIVE_BIN_DIR" >> $GITHUB_PATH

      - name: Build website (do not build already downloaded PDF images)
        run: make website -o build/.pdf

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/website
          retention-days: ${{ inputs.retention_days }}
