name: Compile, archive, link, and run the C code

on:
  workflow_call:
    inputs:
      retention_days:
        required: true
        type: string

jobs:
  build-code:
    name: Compile, archive, link, and run the C code
    runs-on: ubuntu-latest
    steps:
      - name: Update apt-get
        run: sudo apt-get update

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile files without external dependecies
        run: |
          ./.github/scripts/sub-steps.sh make obj_src
          ./.github/scripts/sub-steps.sh make obj_main
          ./.github/scripts/sub-steps.sh make obj_plugins_diffusion

      - name: Create static libraries and diffusion plugin
        run: |
          ./.github/scripts/sub-steps.sh make lib_src
          ./.github/scripts/sub-steps.sh make lib_plugins_diffusion

      - name: Create executables (Link)
        run: make bin

      - name: Run text-outputting demos
        run: |
          ./.github/scripts/sub-steps.sh make txt_array
          ./.github/scripts/sub-steps.sh make txt_algebra
          ./.github/scripts/sub-steps.sh make txt_region
          ./.github/scripts/sub-steps.sh make txt_mesh
          ./.github/scripts/sub-steps.sh make txt_diffusion_steady_state
          ./.github/scripts/sub-steps.sh make txt_diffusion_transient
          ./.github/scripts/sub-steps.sh make txt_graphics

      - name: Install gtk+-3.0
        run: sudo apt-get install -y libgtk-3-dev

      - name: Compile and link plugins
        run: |
          ./.github/scripts/sub-steps.sh make obj_plugins_animation
          ./.github/scripts/sub-steps.sh make obj_plugins_canvas
          ./.github/scripts/sub-steps.sh make lib_plugins_animation
          ./.github/scripts/sub-steps.sh make lib_plugins_canvas

      - name: Run PDF-outputting demos
        run: |
          ./.github/scripts/sub-steps.sh make pdf_filled_window
          ./.github/scripts/sub-steps.sh make pdf_colorbar
          ./.github/scripts/sub-steps.sh make pdf_mesh
          ./.github/scripts/sub-steps.sh make pdf_diffusion_steady_state
          ./.github/scripts/sub-steps.sh make pdf_diffusion_transient

      - name: Run SVG-outputting demos
        run: make svg

      - name: Upload release directory
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/release
          retention-days: ${{ inputs.retention_days }}
