name: Is GitHub Pages enabled?

on:
  workflow_call:
    outputs:
      enabled:
        description: "Whether the 'github-pages' environment is enabled."
        value: ${{ jobs.check-pages-status.outputs.enabled }}
    secrets:
      GH_PAT:
        required: true

jobs:
  check-pages-status:
    name: Is GitHub Pages enabled?
    runs-on: ubuntu-latest
    outputs:
      enabled: ${{ steps.check-pages.outputs.enabled }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if GitHub Pages is enabled
        id: check-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: bash .github/scripts/check-pages-enabled.sh
