name: Deploy to Github Pages

on:
  workflow_call:

jobs:
  deploy-website:
    name: Deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false

    if: github.repository == 'kipiberbatov/cmc'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Set up Github Pages
        uses: actions/configure-pages@v5

      - name: Deploy website to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
