# Build project and deploy to a static website
name: Github Pages

on:
  workflow_run:
    workflows: [release]
    types:
      - completed

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update apt-get
        run: sudo apt-get update

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-release

      - name: Move PDF images of meshes to the appropriate directory
        run: |
          mkdir -p build/release/demo/pdf
          mv linux-release/demo/pdf/mesh build/release/demo/pdf

      - name: Install TeX Live and most used packages
        run: sudo apt-get install -y texlive-latex-extra
      
      - name: Build website (do not build already downloaded PDF meshes)
        run: make website -o demo_pdf_mesh

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/website
          retention-days: 7

  deploy:
    if: github.repository == 'kipiberbatov/idec'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Set up Github Pages
        uses: actions/configure-pages@v5
      
      - name: Deploy website to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
