# Build project and deploy to a static website
name: Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update apt-get
        run: sudo apt-get update

      - name: Install TeX Live and most used packages
        run: sudo apt-get install -y texlive-latex-extra

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Build website
        run: make website

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/website
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Set up Github Pages
        uses: actions/configure-pages@v5
      
      - name: Deploy website to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
