# Build project and deploy to a static website
name: Github Pages

on:
  workflow_run:
    workflows: [release]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-latex-website:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Update apt-get
        run: sudo apt-get update

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Prepare directory for downloading
        run: mkdir -p build/release

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: linux-release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: build/release

      - name: Install TeX Live and most used packages
        run: sudo apt-get install -y texlive-latex-extra

      - name: Build website (do not build already downloaded PDF images)
        run: make website -o build/.pdf

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/website
          retention-days: 7

  deploy:
    if: github.repository == 'kipiberbatov/idec'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-latex-website
    steps:
      - name: Set up Github Pages
        uses: actions/configure-pages@v5

      - name: Deploy website to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
