# Compile, archive, link, and run the C codebase
name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt-get
        run: sudo apt-get update

      - name: Install pkg-config
        run: sudo apt-get install -y pkg-config

      - name: Install gtk+-3.0
        run: sudo apt-get install -y libgtk-3-dev

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile
        run: make obj

      - name: Archive
        run: make lib

      - name: Link
        run: make bin

      - name: Run text-outputing demos
        run: make demo

      - name: Run PDF-outputing demos
        run: make demo_pdf

      - name: Upload release directory
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/release
          retention-days: 7
