name: Run all jobs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-code:
    name: Build code
    uses: ./.github/workflows/build-code.yaml

  build-website:
    name: Build website
    needs: build-code
    uses: ./.github/workflows/build-website.yaml

  check-pages-status:
    name: Check GitHub Pages status
    uses: ./.github/workflows/check-pages-status.yaml

  deploy-website:
    name: Deploy website
    needs: [build-website, check-pages-status]
    if: needs.check-pages-status.outputs.enabled == 'true'
    uses: ./.github/workflows/deploy-website.yaml
